## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(tidyverse)
library(here)
library(SPEI)
library(tsibble)
library(lubridate)
library(tsModel)
library(mgcv)
library(gratia)
library(broom)
library(metRology)
library(clustermq)
library(ipmr)

