---
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(pander)
library(tidyverse)
```

```{r}
df <- tribble(
  ~Description, ~`Deterministic`, ~"Stochastic,\nkernel-resampled", ~ `Stochastic,\nparameter-resampled`,
  
  "Survival",       "$$s(z)$$", "$$s_y(z)$$", "$$s(z;\\theta_{0-36})$$",
  "Growth",         "$G(z^\\prime;z)$", "$G_y(z^\\prime;z)$", "$G(z^\\prime, z;\\theta_{0-36})$",
  
  "Flowering",                     "$p_f(z)$", "$p_{f_y}(z)$", "$p_f(z;\\theta_{0-36})$",
  "Size-specific fecundity",       "$f(z)$", "$f(z)$","$f(z)$",
  "Germination & establishment", "$g$", "$g$", "$g$",
  
  "Seedling survival",              "$s_0$", "$s_{0_y}$", "$s_0(\\theta_{0-36})$",
  "Seedling growth", "$G_0(z^\\prime)$", "$G_{0_y}(z^\\prime)$", "$G_0(z^\\prime;\\theta_{0-36})$",
)

# df
```

```{r results='asis'}
pandoc.table(
  df,
  justify = c("left", "left", "left", "left"),
  #supposed to allow manual line breaks with \n, but not working.
  keep.line.breaks = TRUE,
  style = "multiline"
)
```
